<?php

/**
 * @file
 * Contains commerce_reuse_profile.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_reuse_profile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_reuse_profile module.
    case 'help.page.commerce_reuse_profile':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Reuse Commerce Profile') . '</p>';
      return $output;

    default:
  }
}
